// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopHome.Repository.Concrete.EntityFramework;

namespace ShopHome.Migrations
{
    [DbContext(typeof(ShopHomeContext))]
    [Migration("20200722213419_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopHome.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefon ve Plansetler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Saat ve qolbaqlar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tv,audiove video"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Komputer ve ofis avadanliqlari"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Foto ve video"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Oyun ve Eylence"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Meiset texnikasi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mebel"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tekstil"
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.Fixed_photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SlidersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlidersId");

                    b.ToTable("Fixed_Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Path = "img/photo1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Path = "img/photo2.jpg"
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.Offers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SlidersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlidersId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Xiaomi",
                            Path = "img/Offer1.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "Huawei",
                            Path = "img/Offer2.jpg",
                            Price = 137.30000000000001
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samsung",
                            Path = "img/Offer3.jpg",
                            Price = 129.30000000000001
                        },
                        new
                        {
                            Id = 4,
                            Name = "Xiaomi",
                            Path = "img/Offer4.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 5,
                            Name = "Xiaomi",
                            Path = "img/Offer5.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 6,
                            Name = "Xiaomi",
                            Path = "img/Offer6.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 7,
                            Name = "Xiaomi",
                            Path = "img/Offer7.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 8,
                            Name = "Huawei",
                            Path = "img/Offer8.jpg",
                            Price = 137.30000000000001
                        },
                        new
                        {
                            Id = 9,
                            Name = "Samsung",
                            Path = "img/Offer9.jpg",
                            Price = 129.30000000000001
                        },
                        new
                        {
                            Id = 10,
                            Name = "Xiaomi",
                            Path = "img/Offer10.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 11,
                            Name = "Xiaomi",
                            Path = "img/Offer11.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 12,
                            Name = "Xiaomi",
                            Path = "img/Offer12.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 13,
                            Name = "Xiaomi",
                            Path = "img/Offer13.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 14,
                            Name = "Xiaomi",
                            Path = "img/Offer14.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 15,
                            Name = "Xiaomi",
                            Path = "img/Offer15.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 16,
                            Name = "Xiaomi",
                            Path = "img/Offer16.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 17,
                            Name = "Huawei",
                            Path = "img/Offer17.jpg",
                            Price = 137.30000000000001
                        },
                        new
                        {
                            Id = 18,
                            Name = "Samsung",
                            Path = "img/Offer18.jpg",
                            Price = 129.30000000000001
                        },
                        new
                        {
                            Id = 19,
                            Name = "Xiaomi",
                            Path = "img/Offer19.jpg",
                            Price = 159.30000000000001
                        },
                        new
                        {
                            Id = 20,
                            Name = "Xiaomi",
                            Path = "img/Offer20.jpg",
                            Price = 159.30000000000001
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.Product", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple",
                            Path = "img/telefonlar_Apple.jpg",
                            Price = 100.40000000000001,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung",
                            Path = "img/telefonlar_Samsung.jpg",
                            Price = 354.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xiaomi",
                            Path = "img/telefonlar_Xiaomi.jpg",
                            Price = 425.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Huawei",
                            Path = "img/telefonlar_Huawei.jpg",
                            Price = 432.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "BQ",
                            Path = "img/telefonlar_BQ.jpg",
                            Price = 500.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Honor",
                            Path = "img/telefonlar_Honor.jpg",
                            Price = 354.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "OnePlus",
                            Path = "img/telefonlar_OnePLus.jpg",
                            Price = 354.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hoffmann",
                            Path = "img/telefonlar_Hoffmann.jpg",
                            Price = 354.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sony",
                            Path = "img/telefonlar_Sony.jpg",
                            Price = 354.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Nokia",
                            Path = "img/telefonlar_Nokia.jpg",
                            Price = 354.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Samsung",
                            Path = "img/plansetler_Samsung.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Apple",
                            Path = "img/plansetler_Apple.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Huawei",
                            Path = "img/plansetler_Huawei.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lenovo",
                            Path = "img/plansetler_Lenovo.jpg",
                            Price = 100.40000000000001,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Acer",
                            Path = "img/plansetler_Acer.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Texet",
                            Path = "img/plansetler_Texet.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Wexler",
                            Path = "img/plansetler_Wexler.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "i-Life",
                            Path = "img/plansetler_i-Life.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "MobiWinTab",
                            Path = "img/plansetler_MobiWinTab.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "BQ",
                            Path = "img/plansetler_BQ.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "Xiaomi",
                            Path = "img/plansetler_Xiaomi.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Micromax",
                            Path = "img/plansetler_Micromax.jpg",
                            Price = 354.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Panasonic",
                            Path = "img/ev_telefonlari_Panasonic.jpg",
                            Price = 354.0,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Gigaset",
                            Path = "img/ev_telefonlari_Gigaset.jpg",
                            Price = 354.0,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Qulaqliq qablari",
                            Path = "img/telefon_aksesuarlari_qulaqliq_qabi.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 26,
                            Name = "Telefon ucun tutacaq",
                            Path = "img/telefon_aksesuarlari_qulaqliq_qabi.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 27,
                            Name = "Planset ucun qelem",
                            Path = "img/telefon_aksesuarlari_planset_qelem.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 28,
                            Name = "Powerbanklar",
                            Path = "img/telefon_aksesuarlari_powerbank.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 29,
                            Name = "Qulaqliqlar",
                            Path = "img/telefon_aksesuarlari_qulaqliq.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 30,
                            Name = "Selfi cubuqlari",
                            Path = "img/telefon_aksesuarlari_selfi.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 31,
                            Name = "Qoruyucu ortuk",
                            Path = "img/telefon_aksesuarlari_qoruucu_otruk.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 32,
                            Name = "Qoruyucu suse",
                            Path = "img/telefon_aksesuarlari_qoruyucu_suse.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 33,
                            Name = "Adapterler",
                            Path = "img/telefon_aksesuarlari_adapter.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 34,
                            Name = "Enerji toplayici naqiller",
                            Path = "img/telefon_aksesuarlari_enerji_toplayici_naqil.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 35,
                            Name = "Micro SD kart",
                            Path = "img/telefon_aksesuarlari_microcard.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 36,
                            Name = "Qulaliqlar(Bluetooth)",
                            Path = "img/telefon_aksesuarlari_qulaqliq_bluetooth.jpg",
                            Price = 354.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 39,
                            Name = "Huawei",
                            Path = "img/smartsaat_huawei.jpg",
                            Price = 354.0,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 40,
                            Name = "MYKoronoz",
                            Path = "img/smartsaat_mykronoz.jpg",
                            Price = 354.0,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 41,
                            Name = "Samsung",
                            Path = "img/smartsaat_samsung.jpg",
                            Price = 354.0,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 42,
                            Name = "Xiaomi",
                            Path = "img/smartsaat_xiaomi.jpg",
                            Price = 100.40000000000001,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 43,
                            Name = "Wonlex",
                            Path = "img/smartsaat_wonlex.jpg",
                            Price = 354.0,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 44,
                            Name = "Elari",
                            Path = "img/smartsaat_elari.jpg",
                            Price = 354.0,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 45,
                            Name = "Samsung",
                            Path = "img/smartsaat_elari.jpg",
                            Price = 354.0,
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 46,
                            Name = "Xiaomi",
                            Path = "img/smartqolbaq_xiaomi.jpg",
                            Price = 100.40000000000001,
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 47,
                            Name = "Huawei",
                            Path = "img/smartqolbaq_huawei.jpg",
                            Price = 354.0,
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 48,
                            Name = "MyKronoz",
                            Path = "img/smartqolbaq_mykronoz.jpg",
                            Price = 354.0,
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 49,
                            Name = "Casio",
                            Path = "img/saat_casio.jpg",
                            Price = 354.0,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 50,
                            Name = "Edifice",
                            Path = "img/saat_edifice.jpg",
                            Price = 354.0,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 51,
                            Name = "G-Shock",
                            Path = "img/saat_g-shock.jpg",
                            Price = 354.0,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 52,
                            Name = "Baby-G",
                            Path = "img/saat_baby-g.jpg",
                            Price = 354.0,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 53,
                            Name = "Apple Band",
                            Path = "img/saat_aksesuar_appleband.jpg",
                            Price = 354.0,
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 54,
                            Name = "4K",
                            Path = "img/televizor_4k.jpg",
                            Price = 354.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 55,
                            Name = "LED",
                            Path = "img/televizor_led.jpg",
                            Price = 354.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 56,
                            Name = "QLED",
                            Path = "img/televizor_qled .jpg",
                            Price = 354.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 57,
                            Name = "8K",
                            Path = "img/televizor_8k.jpg",
                            Price = 354.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 58,
                            Name = "TRILUMINOS",
                            Path = "img/televizor_triluminos.jpg",
                            Price = 354.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 59,
                            Name = "NanoCell",
                            Path = "img/televizor_nanoled.jpg",
                            Price = 354.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 61,
                            Name = "Kinoteatr",
                            Path = "img/audio_kinoteatr.jpg",
                            Price = 354.0,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 62,
                            Name = "Smart TV Box",
                            Path = "img/audio_smarttvbox.jpg",
                            Price = 354.0,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 63,
                            Name = "Soundbar",
                            Path = "img/audio_saundbar.jpg",
                            Price = 354.0,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 64,
                            Name = "Portativ akustika",
                            Path = "img/audio_portativakustika.jpg",
                            Price = 354.0,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 65,
                            Name = "Musiqi merkezi",
                            Path = "img/audio_musiqimerkezi.jpg",
                            Price = 354.0,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 66,
                            Name = "Cercive",
                            Path = "img/tv_aksesuar_cercive.jpg",
                            Price = 354.0,
                            SubCategoryId = 13
                        },
                        new
                        {
                            Id = 67,
                            Name = "Sebeke birlesdiricileri",
                            Path = "img/tv_aksesuar_sebekebirlesdirici.jpg",
                            Price = 354.0,
                            SubCategoryId = 13
                        },
                        new
                        {
                            Id = 68,
                            Name = "HDMI naqil",
                            Path = "img/tv_aksesuar_hdmi.jpg",
                            Price = 354.0,
                            SubCategoryId = 13
                        },
                        new
                        {
                            Id = 69,
                            Name = "Asqi aparatlari",
                            Path = "img/tv_aksesuar_asqi.jpg",
                            Price = 354.0,
                            SubCategoryId = 13
                        },
                        new
                        {
                            Id = 70,
                            Name = "Router",
                            Path = "img/komputer_wifi_router.jpg",
                            Price = 354.0,
                            SubCategoryId = 18
                        },
                        new
                        {
                            Id = 71,
                            Name = "Modem",
                            Path = "img/komputer_wifi_modem.jpg",
                            Price = 354.0,
                            SubCategoryId = 18
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guclendirici",
                            Path = "img/komputer_wifi_guclendirici.jpg",
                            Price = 354.0,
                            SubCategoryId = 18
                        },
                        new
                        {
                            Id = 73,
                            Name = "USB WI-FI adapter",
                            Path = "img/komputer_wifi_wifiadapter.jpg",
                            Price = 354.0,
                            SubCategoryId = 18
                        },
                        new
                        {
                            Id = 74,
                            Name = "Macbook",
                            Path = "img/komputer_apple_macbook.jpg",
                            Price = 354.0,
                            SubCategoryId = 20
                        },
                        new
                        {
                            Id = 75,
                            Name = "IMac",
                            Path = "img/komputer_apple_imac.jpg",
                            Price = 354.0,
                            SubCategoryId = 20
                        },
                        new
                        {
                            Id = 76,
                            Name = "DVD oxuyucu",
                            Path = "img/komputer_aksesuar_dvd.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 78,
                            Name = "Kartic",
                            Path = "img/komputer_aksesuar_katric.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 79,
                            Name = "Sebeke birlesdiricileri",
                            Path = "img/komputer_aksesuar_sebekebirlesdirici.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 80,
                            Name = "UPS",
                            Path = "img/komputer_aksesuar_ups.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 81,
                            Name = "Mousepad",
                            Path = "img/komputer_aksesuar_mousepad.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ses guclendirici",
                            Path = "img/komputer_aksesuar_sesguclendirici.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 83,
                            Name = "Mouse",
                            Path = "img/komputer_aksesuar_mouse.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 84,
                            Name = "Klaviatura",
                            Path = "img/komputer_aksesuar_klaviatura.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 85,
                            Name = "Soyutma sistemi",
                            Path = "img/komputer_aksesuar_soyutmasistemi.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 86,
                            Name = "Temizlik vasiteleri",
                            Path = "img/komputer_aksesuar_temizlik.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 87,
                            Name = "Noutbuk ucun cantalar",
                            Path = "img/komputer_aksesuar_canta.jpg",
                            Price = 354.0,
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 88,
                            Name = "Xarici toplayıcılar (HDD/SSD)",
                            Path = "img/komputer_yaddas_hdd_ssd.jpg",
                            Price = 354.0,
                            SubCategoryId = 23
                        },
                        new
                        {
                            Id = 89,
                            Name = "USB toplayici",
                            Path = "img/komputer_yaddas_usb.jpg",
                            Price = 354.0,
                            SubCategoryId = 23
                        },
                        new
                        {
                            Id = 90,
                            Name = "SD kart",
                            Path = "img/komputer_yaddas_sd.jpg",
                            Price = 354.0,
                            SubCategoryId = 23
                        },
                        new
                        {
                            Id = 91,
                            Name = "Linzalar",
                            Path = "img/foto_linzalar.jpg",
                            Price = 354.0,
                            SubCategoryId = 27
                        },
                        new
                        {
                            Id = 92,
                            Name = "Fotoaparatlar ucun cantalar",
                            Path = "img/foto_canta.jpg",
                            Price = 354.0,
                            SubCategoryId = 27
                        },
                        new
                        {
                            Id = 93,
                            Name = "CF kart",
                            Path = "img/foto_cfkart.jpg",
                            Price = 354.0,
                            SubCategoryId = 27
                        },
                        new
                        {
                            Id = 94,
                            Name = "Batareyalar",
                            Path = "img/foto_batareya.jpg",
                            Price = 354.0,
                            SubCategoryId = 27
                        },
                        new
                        {
                            Id = 95,
                            Name = "Stativler",
                            Path = "img/foto_stativ.jpg",
                            Price = 354.0,
                            SubCategoryId = 27
                        },
                        new
                        {
                            Id = 96,
                            Name = "Elektrosamokat",
                            Path = "img/oyun_neqliyat_elektrosamokat.jpg",
                            Price = 354.0,
                            SubCategoryId = 29
                        },
                        new
                        {
                            Id = 97,
                            Name = "Velosipedler",
                            Path = "img/oyun_neqliyat_velsiped.jpg",
                            Price = 354.0,
                            SubCategoryId = 29
                        },
                        new
                        {
                            Id = 98,
                            Name = "Segwat",
                            Path = "img/oyun_neqliyat_segway.jpg",
                            Price = 354.0,
                            SubCategoryId = 29
                        },
                        new
                        {
                            Id = 99,
                            Name = "Playstation",
                            Path = "img/oyun_playstation.jpg",
                            Price = 354.0,
                            SubCategoryId = 30
                        },
                        new
                        {
                            Id = 100,
                            Name = "Jostick",
                            Path = "img/oyun_playstation_joystick.jpg",
                            Price = 354.0,
                            SubCategoryId = 30
                        },
                        new
                        {
                            Id = 101,
                            Name = "Virtual eynek",
                            Path = "img/oyun_playstation_virtualeynek.jpg",
                            Price = 354.0,
                            SubCategoryId = 30
                        },
                        new
                        {
                            Id = 102,
                            Name = "Sukan",
                            Path = "img/oyun_playstation_sukan.jpg",
                            Price = 354.0,
                            SubCategoryId = 30
                        },
                        new
                        {
                            Id = 103,
                            Name = "Oyunlar",
                            Path = "img/oyun_playstation_oyunlar.jpg",
                            Price = 354.0,
                            SubCategoryId = 30
                        },
                        new
                        {
                            Id = 104,
                            Name = "Elektromexaniki konstruktor",
                            Path = "img/oyun_elektromexaniki.jpg",
                            Price = 354.0,
                            SubCategoryId = 32
                        },
                        new
                        {
                            Id = 105,
                            Name = "Velosiped aksesuarlari",
                            Path = "img/oyun_velosiped_aksesuar.jpg",
                            Price = 354.0,
                            SubCategoryId = 32
                        },
                        new
                        {
                            Id = 106,
                            Name = "Avtoyuyucu",
                            Path = "img/evkiciktexnika_avtoyuyucu.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 107,
                            Name = "Tozsoran",
                            Path = "img/evkiciktexnika_tozsoran.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 108,
                            Name = "Utu",
                            Path = "img/evkiciktexnika_utu.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 109,
                            Name = "Tikis masinlari",
                            Path = "img/evkiciktexnika_tikismasini.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 110,
                            Name = "Lampalar",
                            Path = "img/evkiciktexnika_lampalar.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 111,
                            Name = "Buxarli utu",
                            Path = "img/evkiciktexnika_buxarligenerator.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 112,
                            Name = "Utu masasi",
                            Path = "img/evkiciktexnika_utumasasi.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 113,
                            Name = "Paltarqurudan",
                            Path = "img/evkiciktexnika_paltarqurudan.jpg",
                            Price = 354.0,
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 115,
                            Name = "Dondurma duzelden",
                            Path = "img/kicikmeiset_dondurma.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 116,
                            Name = "Qehve",
                            Path = "img/kicikmeiset_qehve.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mikrodalgali soba",
                            Path = "img/kicikmeiset_mikrodalga.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 120,
                            Name = "Toster",
                            Path = "img/kicikmeiset_toster.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 121,
                            Name = "Blender",
                            Path = "img/kicikmeiset_blender.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 123,
                            Name = "Corek bisiren",
                            Path = "img/kicikmeiset_corekbisiren.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 124,
                            Name = "Sireceken",
                            Path = "img/kicikmeiset_sireceken.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 125,
                            Name = "Etceken",
                            Path = "img/kicikmeiset_etceken.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 126,
                            Name = "Mini soba",
                            Path = "img/kicikmeiset_minisoba.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 128,
                            Name = "Dograyici",
                            Path = "img/kicikmeiset_dograyici.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 129,
                            Name = "Izqara",
                            Path = "img/kicikmeiset_izqara.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 130,
                            Name = "Qehveuyuden",
                            Path = "img/kicikmeiset_qehveuyuden.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 131,
                            Name = "Buxarli bisirici",
                            Path = "img/kicikmeiset_buxarlibirsirici.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 132,
                            Name = "Kombayn",
                            Path = "img/kicikmeiset_kombayn.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 133,
                            Name = "Fritoz",
                            Path = "img/kicikmeiset_fritoz.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 134,
                            Name = "Su filtri",
                            Path = "img/kicikmeiset_sufltir.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 136,
                            Name = "Qehvebisiren ucun kapsul",
                            Path = "img/kicikmeiset_qehvebisiren.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 137,
                            Name = "Kabab bisiren",
                            Path = "img/kicikmeiset_kabab.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 138,
                            Name = "Induksiyali pilte",
                            Path = "img/kicikmeiset_induksiyali.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 139,
                            Name = "Qehvebisiren",
                            Path = "img/kicikmeiset_qehvebisiren.jpg",
                            Price = 354.0,
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 140,
                            Name = "Multistayler",
                            Path = "img/gozellik_multistayler.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 141,
                            Name = "Trimmer",
                            Path = "img/gozellik_trimmer.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 142,
                            Name = "Epilyator",
                            Path = "img/gozellik_epilyator,jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 143,
                            Name = "Uz qirxan",
                            Path = "img/gozellik_uzqirxan.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 144,
                            Name = "Menikur desti",
                            Path = "img/gozellik_manikur.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 145,
                            Name = "Terezi",
                            Path = "img/gozellik_terezi.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 146,
                            Name = "Tonometr",
                            Path = "img/gozellik_tonometr.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 147,
                            Name = "Masajor aya ucun",
                            Path = "img/gozellik_masajor.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 148,
                            Name = "Elektrik yorgan",
                            Path = "img/gozellik_elektrikyorgan.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 149,
                            Name = "Termometr",
                            Path = "img/gozellik_termometr.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 150,
                            Name = "Masajor",
                            Path = "img/gozellik_ayaqmasajor.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 151,
                            Name = "Sacqirxan",
                            Path = "img/gozellik_sacqirxan.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 152,
                            Name = "Fen(Hava)",
                            Path = "img/gozellik_fenhava.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 153,
                            Name = "Fen(Masa)",
                            Path = "img/gozellik_fenmasa.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 154,
                            Name = "Fen(Utu)",
                            Path = "img/gozellik_fenutu.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 155,
                            Name = "Fen(Daraq)",
                            Path = "img/gozellik_fendaraq.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 156,
                            Name = "Elektrik dis fircasi",
                            Path = "img/gozellik_disfircasi.jpg",
                            Price = 354.0,
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 157,
                            Name = "Termos",
                            Path = "img/qabqacaq_termos.jpg",
                            Price = 354.0,
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 158,
                            Name = "Tavalar",
                            Path = "img/qabqacaq_tava.jpg",
                            Price = 354.0,
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 159,
                            Name = "Qazanlar",
                            Path = "img/qabqacaq_qazan.jpg",
                            Price = 354.0,
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 160,
                            Name = "Qapaqlar",
                            Path = "img/qabqacaq_qapaq.jpg",
                            Price = 354.0,
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 161,
                            Name = "Metbex desti",
                            Path = "img/qabqacaq_metbexdesti.jpg",
                            Price = 354.0,
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 162,
                            Name = "Bicaq ve bicaq itileyenler",
                            Path = "img/qabqacaq_bicaq.jpg",
                            Price = 354.0,
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 163,
                            Name = "Soyuducu",
                            Path = "img/soyuducu.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 164,
                            Name = "Paltaryuyan",
                            Path = "img/paltaryuyan.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 165,
                            Name = "Qabyuyan",
                            Path = "img/qabyuyan.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 166,
                            Name = "Quruducu masin",
                            Path = "img/quruducumasin.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 167,
                            Name = "Aspirator",
                            Path = "img/aspirator.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 168,
                            Name = "Plite",
                            Path = "img/pilte.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 169,
                            Name = "Soba",
                            Path = "img/soba.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 170,
                            Name = "Solo soba",
                            Path = "img/solosoba.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 171,
                            Name = "Dispenser",
                            Path = "img/dispenser.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 172,
                            Name = "Dondurucu",
                            Path = "img/dondurucu.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 173,
                            Name = "Stabilizator",
                            Path = "img/stabilizator.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 174,
                            Name = "Geyim ucun buxar dolabi",
                            Path = "img/buxardolabi.jpg",
                            Price = 354.0,
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 175,
                            Name = "Yag Radiatorlari",
                            Path = "img/iqlim_radiator.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 176,
                            Name = "Kondisoner",
                            Path = "img/iqlim_kondisoner.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 177,
                            Name = "Iqlim kompleksi",
                            Path = "img/iqlim_iqlimkompleksi.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 178,
                            Name = "Kombi ve Radiatorlar",
                            Path = "img/iqlim_kombi.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 179,
                            Name = "Su qizdirici kalonka",
                            Path = "img/iqlim_kalonka.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 180,
                            Name = "Qaz kalonkasi",
                            Path = "img/iqlim_qazkalonka.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 181,
                            Name = "Spiralli pec",
                            Path = "img/iqlim_pec.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 182,
                            Name = "Konvertor",
                            Path = "img/iqlim_konvektor.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 183,
                            Name = "Isidici",
                            Path = "img/iqlim_isidici.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 184,
                            Name = "Hava nemlendirici",
                            Path = "img/iqlim_nemlendirici.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 185,
                            Name = "Hava temizleyici",
                            Path = "img/iqlim_havatemizleyici.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 186,
                            Name = "Ventilyator",
                            Path = "img/iqlim_vintilyator.jpg",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 187,
                            Name = "Metbex texnikasi ucun aksesuarlar",
                            Path = "img/",
                            Price = 354.0,
                            SubCategoryId = 39
                        },
                        new
                        {
                            Id = 188,
                            Name = "Ev texnikasi ucun aksesuarlar",
                            Path = "img/",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 189,
                            Name = "Temizlik ve yuyucu vasiteleri",
                            Path = "img/",
                            Price = 354.0,
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 190,
                            Name = "Sintifon yorgan",
                            Path = "img/tekstil_yorgan_sintifon.jpg",
                            Price = 354.0,
                            SubCategoryId = 51
                        },
                        new
                        {
                            Id = 191,
                            Name = "Bambu yorgan",
                            Path = "img/tekstil_yorgan_bambu.jpg",
                            Price = 354.0,
                            SubCategoryId = 51
                        },
                        new
                        {
                            Id = 192,
                            Name = "Qaz tuku yorgan",
                            Path = "img/tekstil_yorgan_qaztuku.jpg",
                            Price = 354.0,
                            SubCategoryId = 51
                        },
                        new
                        {
                            Id = 193,
                            Name = "Sintifon yastiq",
                            Path = "img/tekstil_yastiq_sintifon.jpg",
                            Price = 354.0,
                            SubCategoryId = 52
                        },
                        new
                        {
                            Id = 194,
                            Name = "Bambu yastiq",
                            Path = "img/tekstil_yastiq_bambu.jpg",
                            Price = 354.0,
                            SubCategoryId = 52
                        },
                        new
                        {
                            Id = 195,
                            Name = "Qaz tuku yastiq",
                            Path = "img/tekstil_yastiq_qaztuku.jpg",
                            Price = 354.0,
                            SubCategoryId = 52
                        },
                        new
                        {
                            Id = 196,
                            Name = "Tek neferlik pike desti",
                            Path = "img/tekstil_pike_tek.jpg",
                            Price = 354.0,
                            SubCategoryId = 53
                        },
                        new
                        {
                            Id = 197,
                            Name = "Cut neferlik pike desti",
                            Path = "img/tekstil_pike_cut.jpg",
                            Price = 354.0,
                            SubCategoryId = 53
                        },
                        new
                        {
                            Id = 198,
                            Name = "Tek neferlik yataq desti",
                            Path = "img/tekstil_yataq_tek.jpg",
                            Price = 354.0,
                            SubCategoryId = 54
                        },
                        new
                        {
                            Id = 199,
                            Name = "Iki neferlik yataq desti",
                            Path = "img/tekstil_yataq_iki.jpg",
                            Price = 354.0,
                            SubCategoryId = 54
                        },
                        new
                        {
                            Id = 200,
                            Name = "Usaq yataq desti",
                            Path = "img/tekstil_yataq_usaq.jpg",
                            Price = 354.0,
                            SubCategoryId = 54
                        },
                        new
                        {
                            Id = 201,
                            Name = "Usaq edyali",
                            Path = "img/tekstil_edyal_usaq.jpg",
                            Price = 354.0,
                            SubCategoryId = 55
                        },
                        new
                        {
                            Id = 202,
                            Name = "Edyallar",
                            Path = "img/tekstil_edyal_edyal.jpg",
                            Price = 354.0,
                            SubCategoryId = 55
                        },
                        new
                        {
                            Id = 203,
                            Name = "Hamam desmali",
                            Path = "img/tekstil_desmal_hamam.jpg",
                            Price = 354.0,
                            SubCategoryId = 56
                        },
                        new
                        {
                            Id = 204,
                            Name = "Uz desmali",
                            Path = "img/tekstil_desmal_uz.jpg",
                            Price = 354.0,
                            SubCategoryId = 56
                        },
                        new
                        {
                            Id = 205,
                            Name = "Qadin hamam xalati",
                            Path = "img/tekstil_xalat_qadin.jpg",
                            Price = 354.0,
                            SubCategoryId = 57
                        },
                        new
                        {
                            Id = 206,
                            Name = "Kisi hamam xalati",
                            Path = "img/tekstil_xalat_kisi.jpg",
                            Price = 354.0,
                            SubCategoryId = 57
                        },
                        new
                        {
                            Id = 207,
                            Name = "Usaq hamam xalati",
                            Path = "img/tekstil_xalat_usaq.jpg",
                            Price = 354.0,
                            SubCategoryId = 57
                        },
                        new
                        {
                            Id = 208,
                            Name = "Yataq otruyu desti",
                            Path = "img/tekstil_yataqostuyu.jpg",
                            Price = 354.0,
                            SubCategoryId = 58
                        },
                        new
                        {
                            Id = 209,
                            Name = "Usaq yataq otruyu",
                            Path = "img/tekstil_yataqostuyu_usa.jpg",
                            Price = 354.0,
                            SubCategoryId = 58
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SlidersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlidersId");

                    b.ToTable("Slider");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Path = "img/slider1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Path = "img/slider2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Path = "img/slider3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Path = "img/slider4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Path = "img/slider5.jpg"
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.Sliders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.SubCategory", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Mobil telefonlar"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Plansetler"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Ev ve ofis telefonlari"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Elektron kitab"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Aksesuarlar"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Smart saatlar"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Smart qolbaqlar"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Saatlar"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Aksesuarlar"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Televizor ve proyektorlar"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "Audio,video"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Televizor altligi"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Aksesuarlar"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Name = "Monoblok"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Name = "Sistem bloklari"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Name = "Printer"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Name = "Wifi ve Sebeke avadanliqlari"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Name = "Noutbook aksesuarlari"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Name = "Proqram teminati"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Name = "Yaddas"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Name = "Anti cap fotoaparatlar"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Name = "Videoqeydiyyatci"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Name = "Pesekar fotoaparatlar"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Name = "Foto aksesuar"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Name = "Videokameralar"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Name = "Neqliyyat"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Name = "PlayStation Store"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            Name = "Oyun konsollari"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            Name = "Aksesuarlar"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            Name = "Ev üçün kiçik məişət texnikasi"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 7,
                            Name = "Mətbəx üçün kiçik məişət texnikası"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            Name = "Gözəllik və sağlamlıq"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 7,
                            Name = "Qab-qacaq"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 7,
                            Name = "Böyük məişət texnikası"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 7,
                            Name = "İqlim texnikası"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 7,
                            Name = "Aksesuarlar"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            Name = "Qonaq mebeli"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 8,
                            Name = "Uşaq mebeli"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 8,
                            Name = "Yataq mebeli"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 8,
                            Name = "Yumşaq mebellər"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 8,
                            Name = "TV stendlər"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 8,
                            Name = "Dəhliz dolabları"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 8,
                            Name = "Jurnal masalar"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            Name = "Mətbəx masaları"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 8,
                            Name = "Mətbəx stulları"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 8,
                            Name = "Mətbəx mebeli"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 9,
                            Name = "Masa örtüyü"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 9,
                            Name = "Yorğanlar"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 9,
                            Name = "Yastıqlar"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 9,
                            Name = "Pikə dəsti"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 9,
                            Name = "Yataq dəsti"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 9,
                            Name = "Ədyallar"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 9,
                            Name = "Dəsmallar"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 9,
                            Name = "Hamam xalatı"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 9,
                            Name = "Yataq örtüyü / yataq dəsti"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 9,
                            Name = "Hamam xalçası"
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.Today_is_offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SlidersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlidersId");

                    b.ToTable("Today_Is_Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Xiaomi",
                            Path = "img/today_offer1.jpg",
                            Price = 332.69999999999999
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lenovo",
                            Path = "img/today_offer2.jpg",
                            Price = 302.69999999999999
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samsung",
                            Path = "img/today_offer3.jpg",
                            Price = 222.90000000000001
                        },
                        new
                        {
                            Id = 4,
                            Name = "Xiaomi",
                            Path = "img/today_offer4.jpg",
                            Price = 332.69999999999999
                        },
                        new
                        {
                            Id = 5,
                            Name = "Xiaomi",
                            Path = "img/today_offer5.jpg",
                            Price = 332.69999999999999
                        },
                        new
                        {
                            Id = 6,
                            Name = "Xiaomi",
                            Path = "img/today_offer6.jpg",
                            Price = 332.69999999999999
                        },
                        new
                        {
                            Id = 7,
                            Name = "Xiaomi",
                            Path = "img/today_offer7.jpg",
                            Price = 332.69999999999999
                        },
                        new
                        {
                            Id = 8,
                            Name = "Xiaomi",
                            Path = "img/today_offer8.jpg",
                            Price = 332.69999999999999
                        },
                        new
                        {
                            Id = 9,
                            Name = "Xiaomi",
                            Path = "img/today_offer9.jpg",
                            Price = 332.69999999999999
                        },
                        new
                        {
                            Id = 10,
                            Name = "Xiaomi",
                            Path = "img/today_offer10.jpg",
                            Price = 332.69999999999999
                        });
                });

            modelBuilder.Entity("ShopHome.Entity.discount_of_the_day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SlidersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlidersId");

                    b.ToTable("Discount_Of_The_Days");
                });

            modelBuilder.Entity("ShopHome.Entity.last_15_sold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SlidersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlidersId");

                    b.ToTable("Last_15_Solds");
                });

            modelBuilder.Entity("ShopHome.Entity.Fixed_photo", b =>
                {
                    b.HasOne("ShopHome.Entity.Sliders", null)
                        .WithMany("fixed_Photos")
                        .HasForeignKey("SlidersId");
                });

            modelBuilder.Entity("ShopHome.Entity.Offers", b =>
                {
                    b.HasOne("ShopHome.Entity.Sliders", null)
                        .WithMany("Offers")
                        .HasForeignKey("SlidersId");
                });

            modelBuilder.Entity("ShopHome.Entity.Product", b =>
                {
                    b.HasOne("ShopHome.Entity.SubCategory", null)
                        .WithMany("ProductList")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopHome.Entity.Slider", b =>
                {
                    b.HasOne("ShopHome.Entity.Sliders", null)
                        .WithMany("Slider")
                        .HasForeignKey("SlidersId");
                });

            modelBuilder.Entity("ShopHome.Entity.SubCategory", b =>
                {
                    b.HasOne("ShopHome.Entity.Category", null)
                        .WithMany("SubCategoryList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopHome.Entity.Today_is_offer", b =>
                {
                    b.HasOne("ShopHome.Entity.Sliders", null)
                        .WithMany("GetToday_Is_Offers")
                        .HasForeignKey("SlidersId");
                });

            modelBuilder.Entity("ShopHome.Entity.discount_of_the_day", b =>
                {
                    b.HasOne("ShopHome.Entity.Sliders", null)
                        .WithMany("discount_Of_The_Days")
                        .HasForeignKey("SlidersId");
                });

            modelBuilder.Entity("ShopHome.Entity.last_15_sold", b =>
                {
                    b.HasOne("ShopHome.Entity.Sliders", null)
                        .WithMany("last_15_Solds")
                        .HasForeignKey("SlidersId");
                });
#pragma warning restore 612, 618
        }
    }
}
